name: Upload Binary to Release

on:
  workflow_dispatch:
  release:
    types: [created, published]
  push:
    tags:
      - v*

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Firmware/Liv_Flo_Sign/.pio/build/custom_board/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
